[tool.poetry]
name = "brownie-safe"
version = "0.8.0"
description = "Build complex Gnosis Safe transactions and safely preview them in a forked environment."
authors = ["banteg"]
license = "MIT"
repository = "https://github.com/banteg/brownie-safe"
readme = "readme.md"

[tool.poetry.dependencies]
python = ">=3.8"
eth-brownie = ">=1.19.3"
safe-eth-py = ">=5.5"
trezor = ">=0.13.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
